### ISSUE TITLE
forward http => https

### ISSUE THREAD

**Issue by bengreenier** [hashtag-include/arewegood-web#4]
we should deprecate `http` protocol, in favor of `https`. this will have connotations in the sdk, and the proxy.

**Comment by trjast** [comment]
full ssl support is added

**Comment by bengreenier** [comment]
A side effect of this is breaking all the other components. Did you solve this in a pr or merge it right in. Hint: pr is the right answer. @trjast.

**Comment by trjast** [comment]
Merged it right in, because if you look at slack you'll see why. It required pushing the initial changeset and patching prod a dozen or so times. I should have merged the initial changeset from a pr though.

Which components does this break? I would imagine all requests would still go through but just get redirected to use https

Sent from my iPhone

On Feb 13, 2015, at 4:46 PM, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:

A side effect of this is breaking all the other components. Did you solve this in a pr or merge it right in. Hint: pr is the right answer. @trjast.

Sent from my iPhone

> On Feb 13, 2015, at 3:30 PM, Trevor Stevens <notifications@github.com<mailto:notifications@github.com>> wrote:
> 
> Redirect added
> 
> ## 
> 
> Reply to this email directly or view it on GitHub.

##

**Comment by bengreenier** [comment]
Okay, ill verify, I'm not sure if I'm right about this anymore. 

Sent from Windows Mail

From: Trevor Stevens
Sent: ‎Friday‎, ‎February‎ ‎13‎, ‎2015 ‎4‎:‎53‎ ‎PM
To: hashtag-include/arewegood-web
Cc: Ben Greenier

Merged it right in, because if you look at slack you'll see why. It required pushing the initial changeset and patching prod a dozen or so times. I should have merged the initial changeset from a pr though.

Which components does this break? I would imagine all requests would still go through but just get redirected to use https

Sent from my iPhone

On Feb 13, 2015, at 4:46 PM, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:

A side effect of this is breaking all the other components. Did you solve this in a pr or merge it right in. Hint: pr is the right answer. @trjast.

Sent from my iPhone

> On Feb 13, 2015, at 3:30 PM, Trevor Stevens <notifications@github.com<mailto:notifications@github.com>> wrote:
> 
> Redirect added
> 
> ## 
> 
> Reply to this email directly or view it on GitHub.

##
